### ISSUE TITLE
Support plausible.io?

### ISSUE THREAD

**Issue by kissu** [Destiner/astro-analytics#5]
Hi, is it possible to support [Plausible](https://plausible.io/) please? 🙏🏼

**Comment by Destiner** [comment]
Hey @kissu, I added Plausible. If you could try it that would be great.

**Comment by Pukimaa** [comment]
While this is great I would love if you could add support for a custom script. Because if you selfhost it the script isn't hosted on plausible.io

I would add the script source as optional and if it isn't provided it just fallbacks to the plausible.io one

**Comment by Destiner** [comment]
@Pukimaa I added optional `src` prop, which you can use to replace the default script source.

**Comment by Pukimaa** [comment]
Ye wasn't clear at the first moment...I added a PR to clarify it: #6
